name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [12]
        script: ["ci:test"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock', './yarn.lock') }}
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --immutable
      - name: Run integration tests
        run: yarn ${{ matrix.script }}
