on:
  push:
    branches:
      - release/simple-project

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    # Do not run on forks
    if: github.repository == 'cpro-js/workspace-test'
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4.0.2
        with:
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.CPRO_JS_RELEASE_PLEASE_TOKEN }}

  publish-npm:
    # publish only when released
    if: ${{ needs.release-please.outputs.releases_created == true || needs.release-please.outputs.releases_created == 'true' }}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - name: Install packages
        run: npm ci
      - name: Publish packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CPRO_JS_NPM_TOKEN }}
